### ISSUE TITLE
Клиент не возвращает uuid при повторной регистрации чека

### ISSUE THREAD

**Issue by vhar** [0x6368656174/atol-online#6]
При попытке повторно зарегистрировать чек получаем ClientException "В системе существует чек с external_id :..."
Однако, согласно описанию API - это не является фатальной ошибкой, так как кроме самой ошибки возвращается uuid данного чека, что весьма полезно, а иногда и просто необходимо.

> Идентификатор документа внешней системы, уникальный
> среди всех документов, отправляемых в данную группу
> ККТ. Тип данных – строка.
> Предназначен для защиты от потери документов при
> разрывах связи – всегда можно подать повторно чек с таким
> же external_id. Если данный external_id известен системе,
> будет возвращен UUID, ранее присвоенный этому чеку,
> иначе чек добавится в систему с присвоением нового UUID.
> Максимальная длина строки – 128 символов.

**Comment by 0x6368656174** [comment]
closed by #8
